spring:
  ##mongo配置
#  data:
#    mongodb:
#      database: test
#      host: 115.159.202.204
#      port: 10050


  ##mysql配置
  datasource:
    ##Mybatis库
    url: jdbc:mysql://115.159.202.204:32772/test_schema?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
#    schema:
#      - "classpath:db/schema.sql"
#    data:
#      - "classpath:db/data.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
#    ##JPA主库
#    primary:
#      url: jdbc:mysql://115.159.202.204:32772/test_schema?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#        minimum-idle: 5
#        connection-test-query: SELECT 1 FROM DUAL
#        maximum-pool-size: 20
#        auto-commit: true
#        idle-timeout: 30000
#        pool-name: PrimaryHikariCP
#        max-lifetime: 60000
#        connection-timeout: 30000
#    ##JPA从库
#    second:
#      url: jdbc:mysql://127.0.0.1:3306/test_schema?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      hikari:
#        minimum-idle: 5
#        connection-test-query: SELECT 1 FROM DUAL
#        maximum-pool-size: 20
#        auto-commit: true
#        idle-timeout: 30000
#        pool-name: SecondHikariCP
#        max-lifetime: 60000
#        connection-timeout: 30000
#  ##JPA配置
#  jpa:
#    ##主库
#    primary:
#      show-sql: true
#      generate-ddl: true
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#      open-in-view: true
#    #从库
#    second:
#      show-sql: true
#      generate-ddl: true
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#      open-in-view: true

##Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xkcoding.orm.mybatis.plus.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.xkcoding: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.xkcoding.orm.mybatis.plus.mapper: trace
