filebeat.prospectors:
  - type: log
    enabled: true
    paths:
      - /logs/risk-yazx-data/phoneNoCheck/risk-yazx-data-phoneNoCheck.log
    multiline:
      pattern: '^\s*[0-9]{4}-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]'
      negate: true
      match: after
output.kafka:
  version: 0.9.0.1
  enabled: true
  hosts: ["10.30.200.155:15386","10.29.196.183:15386","10.169.152.252:15386"]
  topic: RISK_YAZX_PHONENO_CHECK
  codec.format:
    string: '%{[message]}'
  partition.round_robin:
    reachable_only: true
  keep_alive: 10s