
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 0
    maxActive: 2
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    url: 'jdbc:sqlite::memory:'
#    username: root
#    password: root